GIScience/sketch-map-tool

analyses/modules/analysis_landmarks.py

While the method `create_plot` is already only called in case such an error cannot occur, it makes sense to adjust the method itself so that future changes do not produce this error

Avoid potential division by zero in landmark density analysis

---

sketch_map_tool/static/style/base.css
sketch_map_tool/static/style/index.css
sketch_map_tool/templates/index2.html

Arrows now keep being centered in their columns

fix misaligned arrows in index2.html, especially when scaling the page

---

.github/workflows/python.yml
Dockerfile
docs/development-setup.md
poetry.lock
pyproject.toml

The dependency management of Poetry has an issue installing `gdal` with `numpy` to enable `gdal_array`. If you install them with poetry, `gdal` comes without `gdal_array`.
The proposed workaround for now is to install first numpy and then pygdal with pip and afterwards run the regular poetry install. This workaround should be fixed later by a proper bugfix using poetry.

fix setup with numpy and gdal

---

sketch_map_tool/routes.py
tests/conftest.py

mimetype information is not enough in all cases. My smartfone downloaded geojson as *.bin.
So explicitly add download_names seems to be a good idea.

add explicit download names, esp. file-endings

---

sketch_map_tool/map_generation/generate_pdf.py

Correct docstring, which contained an outdated parameter and return description. Maybe we should add linters again to avoid such wrong documentation?

Update generate_pdf.py: Update Docstring

---

docker-compose.yaml
sketch_map_tool/__init__.py

A built-in periodic task will delete the results

feat(celery/db): enable beat to run backup cleanup

---

sketch_map_tool/map_generation/generate_pdf.py

Fix #203: Close matplotlib scale figure after saving

---

client-src/create/form.js
client-src/create/index.js
client-src/create/map.js

Potential uses:
You want to make sure to have the same selection at two separate sessions, e.g. to inspect changes after a mapathon, so you need the center point (and orientation, zoom and paper format settings). Or to simply improve usability in a way that you don't have to always search / drag to the wider area you are concerned with, but directly loading the map focussed on it.

Close #186 and fix #250 Allow bookmarking and sharing of map selections (center points)

---

config/sample.config.toml
sketch_map_tool/config.py
sketch_map_tool/exceptions.py
sketch_map_tool/routes.py
tests/conftest.py
tests/integration/test_upload.py
tests/unit/test_config.py
tests/unit/test_routes_api.py
tests/unit/test_routes_create.py

As we once defined 80 uploads per user as upper boundary of what should be sufficient for the vast majority of uses, I set a value slightly above that (100). In case one needs more, one can of course always split up the uploads and later merge the files in a GIS. As this value is, therefore, theoretically reasoned and should be valid for all instances of the tool, it is not included in the config. However, if you deem it sensible to set this value in the config, I can change it accordingly.

Close #207: Limit the max. number of uploaded files

---

client-src/shared/poll/poll.js
client-src/shared/poll/pollUntilValid.js

Previously a network error stopped the result page from polling and the user only saw an endless spinner. Now polling goes on even if flask is temporarily not available, e.g. while restarting. Polling goes on until flask sends a status of SUCCESS or ERROR
Closes: #280

fix(frontend): improve network error handling while waiting for results

---

.github/workflows/html-css-javascript-linting.yml
.github/workflows/js-css.yml
.github/workflows/python.yml
client-src/base/base.css
client-src/create/form.js
client-src/create/index.js
client-src/create/map.js
client-src/create/messageController.js
sketch_map_tool/templates/create.html

- validate bbox and do not allow sending form if bbox crosses the antimeridian
- notify user with warning and display antimeridian if it is in the selected bbox
Refs: #279

fix (map-generation, ui): avoid selecting invalid bboxes

---

sketch_map_tool/routes.py
sketch_map_tool/tasks.py
sketch_map_tool/upload_processing/qr_code_reader.py

feat(sketch-map): add attributions file

---

sketch_map_tool/templates/help.html

Fix figure caption: one line was removed > check what happens in Crowdin with the translations (should be fine now as Jochen has changed the Crowdin settings)

Update help page

---

client-src/shared/poll/poll.js
sketch_map_tool/routes.py

previously only error messages for error which did not return with HTTP 500 status code got displayed in the information.
The problem has been that in the case of 500 HTTP status code the error message of the backend error has not been shown to the user.

fix(ui): display error information also for 500

---

sketch_map_tool/upload_processing/clip.py

fix(clip): limit number of keypoints

---

client-src/digitize/index.js
client-src/shared/poll/poll.js
poetry.lock
pyproject.toml
scripts/flask.sh
sketch_map_tool/database/client_flask.py
sketch_map_tool/routes.py
sketch_map_tool/templates/digitize.html
sketch_map_tool/upload_processing/clip.py
tests/integration/test_routes.py

After deployment run: 
```
UPDATE blob
SET consent = true
WHERE ts is not NULL;
```
Update docs on confluence.
Closes #455

Enable opt-out of the usage of uploaded sketch maps for the improvement of the tool

---

sketch_map_tool/templates/digitize.html

refactor(ui): update consent text on /digitize page

---

docker-compose.yaml

Restores resource limits of docker compose services.
Reference: https://github.com/GIScience/sketch-map-tool/commit/4295a21ad32fc74ab29d18b0510ca1e829b70f0a

build: limit resources of docker compose services

---

sketch_map_tool/database/client_celery.py
sketch_map_tool/tasks.py
tests/integration/test_celery_tasks.py
tests/integration/test_database_client_celery.py

clean-up blobs based on file ids not uuid to avoid remove blobs with same uuid but uploaded separately.

fix(db): clean-up blobs based on file ids

---

pyproject.toml
uv.lock

Experimental switch from Poetry to uv
```bash
…/smt on  uv ❯ uv --version
uv 0.5.13
…/smt on  uv ❯ rm -r venv && uv cache clean
…/smt on  uv ❯ rm uv.lock
…/smt on  uv ❯ uv sync && uv add duckdb
took 10m14s ❯
```
```bash
~…/smt on  main ❯ poetry --version
Poetry (version 1.8.3)
~…/smt on  main ❯ poetry env remove 3.12
~…/smt on  main ❯ rm -rf ~/.cache/pypoetry/
~…/smt on  main ❯ rm poetry.lock
~…/smt on  main ❯ poetry install && poetry add duckdb
took 12m38s
```
```bash
…/smt on  uv ❯ uv add black
Resolved 191 packages in 4.34s
Prepared 3 packages in 3.08s
Installed 3 packages in 21ms
took 8s
```
```bash
…/smt on  main ❯ poetry add ruff
Updating dependencies
Resolving dependencies... (14.7s)
took 18s
```

build: switch to uv

---

Dockerfile
compose.yaml

Improve Docker build image:
- use build caches for `apt` and `poetry`
- split build and runtime images
- use Debian-based python (slim) image, not Ubuntu
- do not use poetry in runtime image, just the venv
Idea comes from: https://medium.com/@albertazzir/blazing-fast-python-docker-builds-with-poetry-a78a66f5aed0

Docker: split dockerfile in runtime and builder

---

docs/development-setup.md

* macOS poetry can be installed directly via `brew`
* replace `poetry shell` command
* explicitly use `poetry run` or activate the poetry environment as documented by poetry
To be decided:
* Which variant is better for the docs? Always use `poetry run` or activate poetry env?
Open ToDos for docs:
Closes #546

Update development setup docs

---

sketch_map_tool/database/client_flask.py
sketch_map_tool/routes.py
tests/unit/conftest.py
tests/unit/test_routes_api_download.py
tests/unit/test_routes_api_status.py

Remove functions which were needed for the amount of time Celery keeps results in the Result Store (24h) during transition to new code.

refactor: remove unused code
