.gitignore

Update gitignore. Only additions. No deletions.

update gitignore using Python GitHub template

---

.github/workflows/python.yml
.hooks/pre-commit
.hooks/pre_commit_stages/stage_eslint.py
.hooks/pre_commit_stages/stage_htmlhint.py
.hooks/pre_commit_stages/stage_mypy.py
.hooks/pre_commit_stages/stage_pylint.py
.hooks/pre_commit_stages/stage_stylelint.py
CHANGELOG.md
poetry.lock
pyproject.toml
setup.cfg
sketch_map_tool/analyses/helpers.py
sketch_map_tool/analyses/html_gen/analyses_output_generator.py
sketch_map_tool/analyses/modules/analysis_base.py
sketch_map_tool/analyses/modules/analysis_completeness.py
sketch_map_tool/analyses/modules/analysis_currentness.py
sketch_map_tool/analyses/modules/analysis_landmarks.py
sketch_map_tool/analyses/modules/analysis_sources.py
sketch_map_tool/analyses/pdf_gen/pdf_gen.py
sketch_map_tool/analyses/run_analyses.py
sketch_map_tool/app.py
sketch_map_tool/constants.py
sketch_map_tool/helper_modules/bbox_utils.py
sketch_map_tool/helper_modules/progress.py

add auto-formatters black and isort

---

CHANGELOG.md
docs/development-setup.md
poetry.lock
pyproject.toml
sketch_map_tool/app2.py
sketch_map_tool/templates/base.html
sketch_map_tool/templates/create-results.html
sketch_map_tool/templates/create.html
sketch_map_tool/templates/index2.html
tests/test_app.py
tests/test_app_create.py

feat(flask): define new endpoints & add templates for creating a new sketch map:
- /create
- /create/result
- /(create/results/status)
Related to #53

feat(flask): define new endpoints & add templates for creating a new sketch map

---

sketch_map_tool/static/style/base.css
sketch_map_tool/templates/create-results.html

to create_result HTML template

feat(flask): add report and map download buttons

---

.github/workflows/python.yml
CHANGELOG.md

ci: run python tests

---

CHANGELOG.md
Dockerfile
config/sample.config.toml
docker-compose.yaml
docs/development-setup.md
poetry.lock
pyproject.toml
scripts/run_celery.sh
scripts/run_flask.sh
setup.cfg
sketch_map_tool/__init__.py
sketch_map_tool/config.py
sketch_map_tool/data_store/client.py
sketch_map_tool/routes.py
sketch_map_tool/tasks.py

Based on: https://flask.palletsprojects.com/en/2.2.x/patterns/celery/
~- [ ] Add tests~

use celery as queue to run background tasks

---

sketch_map_tool/routes.py
tests/test_routes_api.py

Failing tests in CI are fixed in #90

test: add tests for api endpoint /status

---

CHANGELOG.md
poetry.lock
pyproject.toml
sketch_map_tool/map_generation/__init__.py
sketch_map_tool/map_generation/qr_code.py
tests/conftest.py
tests/unit/test_qr_code.py

feat: add module to generate qr-codes as svg & rlg

---

client-src/create/map.js

do not allow map rotation

---

client-src/base/base.css
client-src/base/results.css
client-src/create/create.css
client-src/create/form.js
client-src/shared/poll/poll.js
sketch_map_tool/exceptions.py
sketch_map_tool/oqt_analyses/oqt_client.py
sketch_map_tool/routes.py
sketch_map_tool/templates/create-results.html
sketch_map_tool/templates/create.html
sketch_map_tool/templates/digitize-results.html

restrict map to higher zoomlevels

---

client-src/digitize-results/index.js
sketch_map_tool/data_store/client.py
sketch_map_tool/definitions.py
sketch_map_tool/routes.py
sketch_map_tool/tasks.py
sketch_map_tool/validators.py
tests/unit/test_validators.py

Response with georeferenced sketch maps as ZIP and with detected markings as GeoJSON

feat: start two celery workflows for digitization

---

sketch_map_tool/database/client.py
sketch_map_tool/routes.py
sketch_map_tool/tasks.py
tests/integration/test_database_client.py
tests/unit/test_routes_api.py
tests/unit/test_routes_create.py

[feat(db): add context manager to open/close conn](https://github.com/GIScience/sketch-map-tool/pull/197/commits/13f8d913d9015e29a040b7dc01e5f315c3d9eb20)
[refactor(db): use context manager to manage conn](https://github.com/GIScience/sketch-map-tool/pull/197/commits/febba1e9ed28adf80051eeb0d7edc4c76e41e6a1)

implement context manager to open and close database connection

---

sketch_map_tool/database/client.py
sketch_map_tool/routes.py
sketch_map_tool/tasks.py
tests/conftest.py
tests/integration/test_database_client.py
tests/integration/test_tasks_digitized_results.py

Files from db celery chain

---

sketch_map_tool/oqt_analyses/generate_pdf.py
sketch_map_tool/oqt_analyses/oqt_client.py

This PR applies minor changes to the OQT integration into SMT. It should be integrated after the release of OQT 0.15.0. See also https://github.com/GIScience/ohsome-quality-analyst/milestone/12
Closes #239

Update OQT to version 0.15.0

---

.gitignore
config/sample.config.toml
docs/configuration.md
docs/development-setup.md
poetry.lock
pyproject.toml
sketch_map_tool/config.py
sketch_map_tool/upload_processing/ml_models.py
tests/unit/test_config.py
tests/unit/test_ml_models.py

- feat(ml-models): download models from neptune.ai
- chore: add ml models to gitignore
- build: move testcontainers to dev dep
- build: add hypothesis and neptune as dependecies

Neptune.ai

---

docs/configuration.md
sketch_map_tool/config.py
tests/integration/conftest.py
tests/integration/test_upload.py
tests/unit/test_config.py
tests/unit/test_validators.py

Avoid the usage of "-" inside envs

fix(config): rename invalid bash environment vars

---

environment.yml
poetry.lock
pyproject.toml
scripts/celery.sh

Dependecies updates

---

sketch_map_tool/upload_processing/merge.py
tests/unit/test_merge.py

fix: do not write CRS property to GeoJSON

---

data/literature.json
docker-compose.yaml
docs/configuration.md
docs/development-setup.md
sketch_map_tool/__init__.py
sketch_map_tool/config.py
sketch_map_tool/tasks.py
tests/unit/test_config.py

Configure logging and discontinue configuration via environment variable

---

sketch_map_tool/__init__.py
sketch_map_tool/definitions.py

fix: only return locale if lang is a language

---

sketch_map_tool/templates/digitize.html

Add text accepting that uploaded data will be used for improvements

---

sketch_map_tool/database/client_flask.py
tests/integration/test_database_client_flask.py

Closes https://github.com/GIScience/sketch-map-tool/issues/441

feat(db): add insert timestamp to blob table

---

poetry.lock
pyproject.toml

build: fix wrong dependency specification

---

sketch_map_tool/templates/digitize-results.html

fix(ui): remove additional </div>

---

sketch_map_tool/database/client_celery.py
sketch_map_tool/database/client_flask.py
sketch_map_tool/routes.py
tests/unit/conftest.py

This PR adds 4 new columns
- map_frame: downloaded TIMESTAMP
- blobs: digitized_uuid UUID, download_vector TIMESTAMP, download_raster TIMESTAMP
and the functionality to updates those colmuns.

Collect if MapFrame and/or Digitized Results are downloaded

---

sketch_map_tool/templates/about.html
sketch_map_tool/templates/case-study-cultural-landmarks.html
sketch_map_tool/templates/digitize-results.html
sketch_map_tool/templates/help.html

Hi, I did some splling checks and created a new branch "spelling-check"for that

Behebung von Rechtschreibfehlern

---

poetry.lock
pyproject.toml
tests/integration/upload_processing/test_detect_markings.py

test(detect-markings): fail if memory limit is exceeded
